version: '3.5'
services: 
  statsd:
    image: statsd/statsd
    ports:
      - 8125:8125/udp
    volumes:
      - ./docker/statsd/config.json:/usr/src/app/config.js
  # graphiteapp:
  #   image: graphiteapp/graphite-statsd
  #   ports:
  #     - 8080:80
  #     - 8125:8125/udp
